const items=[
 {type:'ছড়া',icon:'🌿',title:'বৃষ্টির গান',text:'টাপুর টুপুর বৃষ্টি নামে\nসবুজ পাতায় সুর যে বাজে।\nছোট্ট পাখি ডাকে মিষ্টি স্বরে,\nআনন্দ নামে সবার ঘরে।'},
 {type:'গল্প',icon:'🐱',title:'মিনি আর জাদুর তারা',text:'এক রাতে ছোট্ট মিনি আকাশে একটি জ্বলজ্বলে তারা দেখল।\nতারাটি যেন তাকে পথ দেখিয়ে বলল—ভালো কাজ করলে আলো সবসময় তোমার সাথে থাকবে।\nমিনি সেই রাত থেকে সবাইকে সাহায্য করতে শুরু করল।'},
 {type:'ছড়া',icon:'🌸',title:'ফুলের বাগান',text:'লাল ফুল হাসে, নীল ফুল দোলে,\nপ্রজাপতি উড়ে রঙিন ডানায়।\nমিষ্টি হাওয়ায় মনটা ভরে,\nসকাল আসে নতুন গানে।'},
 {type:'গল্প',icon:'🦜',title:'পাখিটির বন্ধু',text:'একটি ছোট পাখি ঝড়ে তার বাসা হারিয়েছিল।\nএক শিশু তাকে নিরাপদ গাছের ডালে বাসা বানাতে সাহায্য করল।\nপাখিটি প্রতিদিন সকালে বন্ধুটির জানালায় গান গাইত।'}
];
const cards=document.getElementById('cards'),search=document.getElementById('search'),reader=document.getElementById('reader');let current=null;
function render(list=items){cards.innerHTML=list.map((x,i)=>`<article class="card"><div class="card-icon">${x.icon}</div><span class="type">${x.type}</span><h3>${x.title}</h3><p>${x.text.split('\n')[0]}...</p><button class="read" onclick="openReader(${items.indexOf(x)})">পড়ুন ও শুনুন →</button></article>`).join('');document.getElementById('count').textContent=`${list.length}টি লেখা পাওয়া গেছে`}
function openReader(i){current=items[i];document.getElementById('readerType').textContent=current.type;document.getElementById('readerTitle').textContent=current.title;document.getElementById('readerText').textContent=current.text;reader.classList.add('show');reader.scrollIntoView({behavior:'smooth',block:'center'});document.getElementById('favBtn').textContent=localStorage.getItem('fav-'+i)?'♥ পছন্দ হয়েছে':'♡ পছন্দ';document.getElementById('favBtn').onclick=()=>{localStorage.setItem('fav-'+i,'1');document.getElementById('favBtn').textContent='♥ পছন্দ হয়েছে'}}
document.getElementById('closeReader').onclick=()=>reader.classList.remove('show');document.getElementById('speakBtn').onclick=()=>{if(current){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(current.title+'. '+current.text);u.lang='bn-BD';u.rate=.85;speechSynthesis.speak(u)}};document.getElementById('stopBtn').onclick=()=>speechSynthesis.cancel();search.oninput=()=>{let q=search.value.trim().toLowerCase();render(items.filter(x=>(x.title+x.text+x.type).toLowerCase().includes(q)))};document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('dark');document.getElementById('themeBtn').textContent=document.body.classList.contains('dark')?'☀️':'🌙'};render();
